# config file for Pain BMI Client
# stereotrode example
#
# to be done:
# add detect event configuration
# config decoder params
###################################################
[acquisition]          ; acquisition configuration
###################################################
# name of recording regions
Regions = ACC,S1

# channels of each region
ACC = 1-11
S1 = 12-16

# EMG channels
EMG = 31,32

# trodal, single=1/stereotrode=2/tetrode=4
Trodal = 2

# digital input configuration
event = h_laser_on,l_laser_on,pp,vf,opto_pulse,opto_start,detect
h_laser_on = 2
l_laser_on = 3
pp = 36        ;KB1
vf = 37        ;KB2
opto_pulse = 6
opto_start = 7
hargareaves = 8
detect = 9-14

###################################################
[decoder]             ; decoder configuration
###################################################
# decoders to choose from: PLDS/TLDS/ModelFree
# decoders to be implemented: PF_PLDS/Ensembles
Decoders = PLDS1,TLDS1,ModelFree1
##### to be done: single decoder params not configurable yet ####

[PLDS1]
type = PLDS
MaxIter = 200
MaxCpuTime = 30
TrainSeqLength = 200

[TLDS1]
type = TLDS
EmMaxIter = 300
FaMaxIter= 100
EmTol = 0.000001
FaTol = 0.001
TLDS_type = LOGTLDS
TrainSeqLength = 200

[ModelFree1]
type = ModelFree

###################################################
[detector]             ; detector configuration
###################################################
# detectors to choose from: single/greedy
# detectors to be implemented: ccf
# Detectors = single1,single2,single3,single4,single5,single6,greedy1,greedy2,greedy3
# Detectors = single1,single2,single3,single4,greedy1,greedy2,greedy3
Detectors = single1,single2,single3,single4,greedy1,greedy2,greedy3
[single1]; ACC PLDS
# single/greedy/ccf
type = single   
# true/false            
enabled = true
region = ACC
decoder = PLDS1
thresh = 1.65
# the confidence interval will be nStd*std_of_baseline
nStd = 2
# model update mode: manual/auto_trial/auto_always
update = manual
# interval in sec, between current time bin and the end of the baseline(when updating)
interval = 2

[single2]; S1 PLDS   
# single/greedy/ccf
type = single   
# true/false            
enabled = true
region = S1
decoder = PLDS1
thresh = 1.65
# the confidence interval will be nStd*std_of_baseline
nStd = 2
# model update mode: manual/auto_trial/auto_always
update = manual
# interval in sec, between current time bin and the end of the baseline(when updating)
interval = 2

[single3]; ACC ModelFree  
# single/greedy/ccf
type = single   
# true/false            
enabled = true
region = ACC
decoder = ModelFree1
thresh = 3.38
# model update mode: manual/auto_trial/auto_always
update = manual
# interval in sec, between current time bin and the end of the baseline(when updating)
interval = 2

[single4]; S1 ModelFree  
# single/greedy/ccf
type = single   
# true/false            
enabled = true
region = S1
decoder = ModelFree1
thresh = 3.38
# model update mode: manual/auto_trial/auto_always
update = manual
# interval in sec, between current time bin and the end of the baseline(when updating)
interval = 2

[single5]; ACC TLDS
# single/greedy/ccf
type = single   
# true/false            
enabled = true
region = ACC
decoder = TLDS1
thresh = 1.65
# the confidence interval will be nStd*std_of_baseline
nStd = 2
# model update mode: manual/auto_trial/auto_always
update = manual
# interval in sec, between current time bin and the end of the baseline(when updating)
interval = 2

[single6]; S1 TLDS   
# single/greedy/ccf
type = single   
# true/false            
enabled = true
region = S1
decoder = TLDS1
thresh = 1.65
# the confidence interval will be nStd*std_of_baseline
nStd = 2
# model update mode: manual/auto_trial/auto_always
update = manual
# interval in sec, between current time bin and the end of the baseline(when updating)
interval = 2

# one single detector cross higher thresh / all cross lower thresh

[greedy1]; ACC greedy
# single/greedy/ccf
type = greedy
# true/false            
enabled = true
detector = single1,single3
lower_thresh = 1.28,3.38 ; p=0.1
higher_thresh = 1.65,3.38  ; p=0.05

[greedy2]; S1 greedy
# single/greedy/ccf
type = greedy
# true/false            
enabled = true
detector = single2,single4
lower_thresh = 1.28,3.38 ; p=0.1
higher_thresh = 1.65,3.38  ; p=0.05

[greedy3]; nested dual region greedy
# single/greedy/ccf
type = greedy
# true/false            
enabled = true
detector = greedy1,greedy2
lower_thresh = 1.28,1.28 ; p=0.1
higher_thresh = 1.65,1.65  ; p=0.05

[greedy4]; PLDS ACC/S1 greedy
# single/greedy/ccf
type = greedy
# true/false            
enabled = true
detector = single1,single2
lower_thresh = 1.28,1.28 ; p=0.1
higher_thresh = 1.65,1.65  ; p=0.05
###################################################
[DO]        ; digitial output configuration
###################################################
# digital output configuration
output = h_laser_on_event,l_laser_on_event,h_laser_on,l_laser_on,h_laser_warm,l_laser_warm,opto_start,trigger,detect
;rec_trigger = 1
h_laser_on_event = 2
l_laser_on_event = 3
trigger = 4
; IC_cam_evn = 4
; sony_cam_evn = 5
; sony_pulse = 12
h_laser_on = 10
l_laser_on = 11
h_laser_warm = 10
l_laser_warm = 11
; opto_pulse = line2
opto_start = 7
detect = 8-9,13-16

# opto params, in ms
opto_pulse_h = 10
opto_pulse_l = 40
opto_duration = 3000

# laser on duration
stim_time = 5000
warm_time = 45000
