[config_file]
last_path = D:/Silas/onlinePainDecodingGUI/config_files/example.ini
last_folder = D:/Silas/onlinePainDecodingGUI/config_files/
#last_path = E:/Silas/OnlineDecodingSystem/config_files/example.ini
#last_folder = E:/Silas/OnlineDecodingSystem/config_files/